language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  - pip install nose
  - pip install mock
  - pip install requests
  - pip install coveralls
  - pip install aiohttp
script: nosetests --with-coverage --cover-package=fbmq
after_success:
  coveralls